- hosts: all
  become: true
  tasks: 
     - name: create new deployment
       command: kubectl apply -f /home/shahzaib/Deployment.yml
     - name: create new service
       command: kubectl apply -f /home/shahzaib/Service.yml