- hosts: all
  become: true
  tasks: 
     - name: Delete old deployment
       command: microk8s.kubectl delete -f /home/shahzaib/Deployment.yml
     - name: Delete old service
       command: microk8s.kubectl delete -f /home/shahzaib/Service.yml
     - name: create new deployment
       command: microk8s.kubectl apply -f /home/shahzaib/Deployment.yml
     - name: create new service
       command: microk8s.kubectl apply -f /home/shahzaib/Service.yml