kind: Deployment
apiVersion: apps/v1
metadata:
   name: raoshahzaib
spec:
   replicas: 2
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: raoshahzaib
   template:
      metadata:
        labels:
          app: raoshahzaib
      spec:
       containers:
        - name: raoshahzaib
          image: raoshahzaib/pipeline-demo-new:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8080