kind: Service                             
apiVersion: v1
metadata:
  name: raoshahzaib
  labels:
    app: raoshahzaib
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: raoshahzaib                    
  type: NodePort    